### ISSUE TITLE
Don't count incomplete AMD stat reads as Watchdog strikes

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#51]
I have (1) 290X I'm trying to run on a 2x 1060 + 2x 1070 rig.  I can throw a few AMD miners in \Miners from standard MPM and they will calculate profit but after awhile they all catch Watchdog strikes and eventually the miner will stop loading AMD Claymores until the MPM_UG is closed down and restarted.  The miner will load fine and mine fine on the AMD card, I just want it to stay mining instead of have 2 instances of MPM, 1 with UG for NVIDIA and 1 with 2.7.1.4 for AMD

**Comment by UselessGuru** [comment]
Can you please create debug files for OpenGL and GPUs?

I don't have AMD and don't know how a mixed rig presents itself GPU wise.

Would you know what the AMD equivalent of NVIDIA-SMI is?

**Comment by platinum4** [comment]
New codebase completely skips over AMD now, even with Miners in folder:

GPUs.XML

```
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCustomObject</T>
      <T>System.Object</T>
    </TN>
    <MS>
      <S N="Type">NVIDIA</S>
      <Obj N="Device" RefId="1">
        <TN RefId="1">
          <T>System.Object[]</T>
          <T>System.Array</T>
          <T>System.Object</T>
        </TN>
        <LST>
          <Obj RefId="2">
            <TNRef RefId="0" />
            <MS>
              <S N="Type">NVIDIA</S>
              <S N="Device">GeForce GTX 1070</S>
              <S N="Device_Norm">GeforceGTX1070</S>
              <S N="Vendor">NVIDIA Corporation</S>
              <Obj N="Devices" RefId="3">
                <TNRef RefId="1" />
                <LST>
                  <S>0</S>
                  <S>1</S>
                </LST>
              </Obj>
            </MS>
          </Obj>
          <Obj RefId="4">
            <TNRef RefId="0" />
            <MS>
              <S N="Type">NVIDIA</S>
              <S N="Device">GeForce GTX 1060 6GB</S>
              <S N="Device_Norm">GeforceGTX10606GB</S>
              <S N="Vendor">NVIDIA Corporation</S>
              <Obj N="Devices" RefId="5">
                <TNRef RefId="1" />
                <LST>
                  <S>2</S>
                  <S>3</S>
                </LST>
              </Obj>
            </MS>
          </Obj>
        </LST>
      </Obj>
    </MS>
  </Obj>
</Objs>
```

OpenCL1

```


Profile    : FULL_PROFILE
Version    : OpenCL 1.2 CUDA 9.1.84
Name       : NVIDIA CUDA
Vendor     : NVIDIA Corporation
Extensions : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics...}

Profile    : FULL_PROFILE
Version    : OpenCL 2.0 AMD-APP (2442.12)
Name       : AMD Accelerated Parallel Processing
Vendor     : Advanced Micro Devices, Inc.
Extensions : {cl_khr_icd, cl_khr_d3d10_sharing, cl_khr_d3d11_sharing, cl_khr_dx9_media_sharing...}
```

OpenCL2

```


AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, 
                             cl_khr_local_int32_extended_atomics...}
GlobalMemCacheSize         : 245760
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 8589934592
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1835
MaxComputeUnits            : 15
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 2147483648
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 16
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
Name                       : GeForce GTX 1070
ClVersion                  : OpenCL C 1.2 
Platform                   : 
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 390.65

AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, 
                             cl_khr_local_int32_extended_atomics...}
GlobalMemCacheSize         : 245760
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 8589934592
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1784
MaxComputeUnits            : 15
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 2147483648
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 16
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
Name                       : GeForce GTX 1070
ClVersion                  : OpenCL C 1.2 
Platform                   : 
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 390.65

AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, 
                             cl_khr_local_int32_extended_atomics...}
GlobalMemCacheSize         : 163840
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 6442450944
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1708
MaxComputeUnits            : 10
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 1610612736
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 16
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
Name                       : GeForce GTX 1060 6GB
ClVersion                  : OpenCL C 1.2 
Platform                   : 
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 390.65

AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, 
                             cl_khr_local_int32_extended_atomics...}
GlobalMemCacheSize         : 163840
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 6442450944
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1733
MaxComputeUnits            : 10
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 1610612736
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 16
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
Name                       : GeForce GTX 1060 6GB
ClVersion                  : OpenCL C 1.2 
Platform                   : 
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 390.65

AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_fp64, cl_amd_fp64, cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics...}
GlobalMemCacheSize         : 16384
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 64
GlobalMemSize              : 4294967296
ImageSupport               : True
LocalMemSize               : 32768
LocalMemType               : Local
MaxClockFrequency          : 1500
MaxComputeUnits            : 44
MaxConstantArgs            : 8
MaxConstantBufferSize      : 
MaxMemAllocSize            : 4026531840
MaxParameterSize           : 1024
MaxReadImageArgs           : 128
MaxSamplers                : 16
MaxWorkGroupSize           : 256
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {256, 256, 256}
MaxWriteImageArgs          : 64
MemBaseAddrAlign           : 2048
MinDataTypeAlignSize       : 128
Name                       : Hawaii
ClVersion                  : OpenCL C 2.0 
Platform                   : OpenCl.Platform
PreferredVectorWidthChar   : 4
PreferredVectorWidthShort  : 2
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : ProfilingEnable
SingleFpConfig             : FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : Advanced Micro Devices, Inc.
VendorId                   : 4098
Version                    : OpenCL 2.0 AMD-APP (2442.12)
DriverVersion              : 2442.12

AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel, ExecNativeKernel
Extensions                 : {cl_khr_fp64, cl_amd_fp64, cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics...}
GlobalMemCacheSize         : 32768
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 64
GlobalMemSize              : 8536322048
ImageSupport               : True
LocalMemSize               : 32768
LocalMemType               : Global
MaxClockFrequency          : 2800
MaxComputeUnits            : 2
MaxConstantArgs            : 8
MaxConstantBufferSize      : 
MaxMemAllocSize            : 2147483648
MaxParameterSize           : 4096
MaxReadImageArgs           : 128
MaxSamplers                : 16
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 1024}
MaxWriteImageArgs          : 64
MemBaseAddrAlign           : 1024
MinDataTypeAlignSize       : 128
Name                       : Intel(R) Pentium(R) CPU G3440T @ 2.80GHz
ClVersion                  : OpenCL C 1.2 
Platform                   : 
PreferredVectorWidthChar   : 16
PreferredVectorWidthShort  : 8
PreferredVectorWidthInt    : 4
PreferredVectorWidthLong   : 2
PreferredVectorWidthFloat  : 4
PreferredVectorWidthDouble : 2
Profile                    : FULL_PROFILE
QueueProperties            : ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Cpu
Vendor                     : GenuineIntel
VendorId                   : 4098
Version                    : OpenCL 1.2 AMD-APP (2442.12)
DriverVersion              : 2442.12 (sse2)
```

**Comment by UselessGuru** [comment]
Could you please debug filed OpenGL1.xml & OpenGL2.xml (the can be created with https://github.com/UselessGuru/MultiPoolMiner/commit/0bfa1a3f23e0e968b70524d89cb5e984eac3b60b) and then drag/drop them here? I cannot really make use of the text information as posted above :-(

**Comment by platinum4** [comment]
```
**********************
Windows PowerShell transcript start
Start time: 20180111045541
Username: Z97-GAMING-5B\Z97-GAMING-7
RunAs User: Z97-GAMING-5B\Z97-GAMING-7
Configuration Name: 
Machine: Z97-GAMING-5B (Microsoft Windows NT 10.0.16299.0)
Host Application: powershell -version 5.1 -noexit -executionpolicy bypass -windowstyle maximized -command & .\multipoolminer.ps1
Process ID: 9080
PSVersion: 5.1.16299.98
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.98
BuildVersion: 10.0.16299.98
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2018-01-11_04-55-41.txt
Copy-Item : An item with the specified name C:\MultiPoolMiner-master\Debug\Pools already exists.
At C:\MultiPoolMiner-master\MultiPoolMiner.ps1:77 char:5
+     Copy-Item "Pools" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMiner-master\Debug\Pools:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand
Copy-Item : An item with the specified name C:\MultiPoolMiner-master\Debug\Pools already exists.
At C:\MultiPoolMiner-master\MultiPoolMiner.ps1:77 char:5
+     Copy-Item "Pools" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMiner-master\Debug\Pools:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : An item with the specified name C:\MultiPoolMiner-master\Debug\Miners already exists.
At C:\MultiPoolMiner-master\MultiPoolMiner.ps1:78 char:5
+     Copy-Item "Miners" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMiner-master\Debug\Miners:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand
Copy-Item : An item with the specified name C:\MultiPoolMiner-master\Debug\Miners already exists.
At C:\MultiPoolMiner-master\MultiPoolMiner.ps1:78 char:5
+     Copy-Item "Miners" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMiner-master\Debug\Miners:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand

```

**Comment by platinum4** [comment]
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenCl.NativeMethods.clGetPlatformInfo(IntPtr platform, UInt32 paramName, IntPtr paramValueSize, IntPtr paramValue, IntPtr& paramValueSizeRet)
   at OpenCl.Cl.GetInfoString(GetInfoDelegate method, IntPtr handle, UInt32 name)
   at lambda_method(Closure , Object )
   at System.Management.Automation.Adapter.BasePropertyGet(PSProperty property)
   at System.Management.Automation.PSProperty.get_Value()
   at System.Management.Automation.SerializationUtilities.GetPropertyValueInThreadSafeManner(PSPropertyInfo property, Boolean canUseDefaultRunspaceInThreadSafeManner, Boolean& success)
   at System.Management.Automation.InternalSerializer.SerializeProperties(IEnumerable`1 propertyCollection, String name, Int32 depth)
   at System.Management.Automation.InternalSerializer.WritePSObjectProperties(PSObject source, Int32 depth, IEnumerable`1 specificPropertiesToSerialize)
   at System.Management.Automation.InternalSerializer.HandleComplexTypePSObject(Object source, String streamName, String property, Int32 depth)
   at System.Management.Automation.InternalSerializer.WriteOneObject(Object source, String streamName, String property, Int32 depth)
   at System.Management.Automation.InternalSerializer.SerializeProperties(IEnumerable`1 propertyCollection, String name, Int32 depth)
   at System.Management.Automation.InternalSerializer.WritePSObjectProperties(PSObject source, Int32 depth, IEnumerable`1 specificPropertiesToSerialize)
   at System.Management.Automation.InternalSerializer.HandleComplexTypePSObject(Object source, String streamName, String property, Int32 depth)
   at System.Management.Automation.InternalSerializer.WriteOneObject(Object source, String streamName, String property, Int32 depth)
   at Microsoft.PowerShell.Commands.ExportClixmlCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Management.Automation.EnumerableOps.WriteEnumerableToPipe(IEnumerator enumerator, Pipe pipe, ExecutionContext context, Boolean dispose)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.ActionCallInstruction`5.Invoke(Object arg0, Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Management.Automation.Interpreter.CallInstruction.InvokeInstance(Object instance, Object[] args)
   at System.Management.Automation.Interpreter.DynamicInstructionN.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

C:\MultiPoolMiner-master>msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/PowerShell-6.0.0-rc.2-win-x64.msi -qb!

C:\MultiPoolMiner-master>pause
Press any key to continue . . .
```

**Comment by UselessGuru** [comment]
> Copy-Item "Miners" "Debug" -Recurse

You must start off with a clean debug directory.

> Unhandled Exception: System.AccessViolationException:

Totally unrelated. No idea :-(

**Comment by platinum4** [comment]
NVIDIA miners supported only as of 01/16/2018
